# Generated by Django 6.0.3 on 2026-03-22 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField()),
                ('sender_email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('sender_domain', models.CharField(blank=True, default='', max_length=255)),
                ('reply_to', models.EmailField(blank=True, default='', max_length=254)),
                ('predicted_label', models.CharField(choices=[('legitimate', 'Legitimate'), ('spam', 'Spam'), ('phishing', 'Phishing')], max_length=20)),
                ('confidence_score', models.FloatField()),
                ('label_probabilities', models.JSONField(default=dict)),
                ('model_version', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_label', models.CharField(choices=[('legitimate', 'Legitimate'), ('spam', 'Spam'), ('phishing', 'Phishing')], max_length=20)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_reports', to='classifier.emailclassification')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
