# Generated by Django 6.0.3 on 2026-03-22 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailclassification',
            name='extracted_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='emailclassification',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
