# Generated by Django 6.0.3 on 2026-03-22 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0002_emailclassification_extracted_urls_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackreport',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
